### ISSUE TITLE
Chnage from monaco to ace editor

### ISSUE THREAD

**Issue by Covarun** [Charlzk05/Synapse-X-Remake-Synapse-X-Free-Version#1]
Use ace editor is the one that synapse uses

**Comment by Charlzk05** [comment]
Yeah, I changed it 22 days ago
but only on pre-released
I'm also trying to add Tab Controls ykkk, messing around doing sum experiments

[Synapse X Remake - v1.0.1-b.1](https://github.com/Charlzk05/Synapse-X-Remake-Synapse-X-Free-Version/tree/main/Synapse%20X%20Remake%20Betas)

![Screenshot 2022-06-05 064007](https://user-images.githubusercontent.com/104715127/172027579-1f0e0a44-53da-41b7-aadb-9d11eea3dd9c.png)
