### ISSUE TITLE
Attached, but it doesn't execute

### ISSUE THREAD

**Issue by frinkifail** [Charlzk05/Synapse-X-Remake-Synapse-X-Free-Version#14]
ok, it attaches (krnl attached) i put in the key, turn off my antivirus, IT STILL DOESN'T EXECUTE???

**Comment by frinkifail** [comment]
oh yeah, also
the thing here doesn't work too
![image](https://user-images.githubusercontent.com/76682714/206825033-7ca82f89-c937-47bb-b246-fcf2740af286.png)

**Comment by frinkifail** [comment]
it doesn't execute, confirmed

**Comment by Charlzk05** [comment]
> oh yeah, also the thing here doesn't work too ![image](https://user-images.githubusercontent.com/76682714/206825033-7ca82f89-c937-47bb-b246-fcf2740af286.png) Edit: ok nvm it works after a bit of tinkering

you are supposed to right click the selected item

**Comment by frinkifail** [comment]
ok i think krnl api just sucks :skull:
