### ISSUE TITLE
"Krnl not initialized"

### ISSUE THREAD

**Issue by Liriy** [Charlzk05/Synapse-X-Remake-Synapse-X-Free-Version#25]
how i need to fix this?
![image](https://user-images.githubusercontent.com/89244602/216970996-c872c5f2-f93b-4d18-b134-9d37a209b044.png)

**Comment by Charlzk05** [comment]
oh just click the "attach" button

**Comment by Liriy** [comment]
thanks

пн, 6 февр. 2023 г., 7:04 PM Charlzk ***@***.***>:

**Comment by Charlzk05** [comment]
np np np
