### ISSUE TITLE
Krnl not injecting

### ISSUE THREAD

**Issue by MrDimasicTV** [Charlzk05/Synapse-X-Remake-Synapse-X-Free-Version#27]
So after i try to inject, my roblox crash and it gives this message:
![image](https://user-images.githubusercontent.com/52003299/221356142-65deed8f-1d56-46e6-a8a4-e5a831e2198d.png)

**Comment by Charlzk05** [comment]
idk this error either try asking about this error on krnl discord 😭 but anyways thankkk youuu so much for reporting this error

**Comment by aboodka9292** [comment]
i buy the REAL synapse now what?
